"""Add payment system tables

Revision ID: 0cf0ce4fbd3c
Revises: 202ec00a6e83
Create Date: 2025-08-15 18:24:23.061348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf0ce4fbd3c'
down_revision = '202ec00a6e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_renewal', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['id'])
        batch_op.create_foreign_key(None, 'plan', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('auto_renewal')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('plan_id')

    # ### end Alembic commands ###
