"""Define all indexes explicitly in models V3

Revision ID: 202ec00a6e83
Revises: 
Create Date: 2025-04-22 01:06:27.638472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202ec00a6e83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.create_index('ix_conversation_status', ['status'], unique=False)

    with op.batch_alter_table('telegram_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.create_index('ix_telegram_conversation_status', ['status'], unique=False)

    with op.batch_alter_table('telegram_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_telegram_user_last_active', ['last_active'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_user_last_active', ['last_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_last_active')
        batch_op.drop_column('last_active')

    with op.batch_alter_table('telegram_user', schema=None) as batch_op:
        batch_op.drop_index('ix_telegram_user_last_active')
        batch_op.drop_column('last_active')

    with op.batch_alter_table('telegram_conversation', schema=None) as batch_op:
        batch_op.drop_index('ix_telegram_conversation_status')
        batch_op.drop_column('status')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_status')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
