"""Add UserMemory and ConsolidatedConversation tables

Revision ID: 595ad77efa0e
Revises: 0cf0ce4fbd3c
Create Date: 2025-10-07 02:16:52.255649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595ad77efa0e'
down_revision = '0cf0ce4fbd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('subscription_transaction_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('subscription_plan_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('subscription_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'plan', ['plan_id'], ['id'])
        batch_op.create_foreign_key(None, 'transaction', ['transaction_id'], ['id'])

    with op.batch_alter_table('telegram_conversation', schema=None) as batch_op:
        batch_op.drop_constraint('telegram_conversation_telegram_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'telegram_user', ['telegram_user_id'], ['telegram_id'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('transaction_plan_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'plan', ['plan_id'], ['id'])

    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_whatsapp_message_thread_id_timestamp')
        batch_op.create_index('ix_whatsapp_message_thread_id_timestamp', ['thread_id', sa.literal_column('timestamp DESC')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_whatsapp_message_thread_id_timestamp')
        batch_op.create_index('ix_whatsapp_message_thread_id_timestamp', ['thread_id', 'timestamp'], unique=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transaction_plan_id_fkey', 'plan', ['plan_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('telegram_conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('telegram_conversation_telegram_user_id_fkey', 'telegram_user', ['telegram_user_id'], ['telegram_id'], ondelete='CASCADE')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscription_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('subscription_plan_id_fkey', 'plan', ['plan_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('subscription_transaction_id_fkey', 'transaction', ['transaction_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
